<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\billpg.WWWAuthenticateTools\billpg.WWWAuthenticateTools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\test-vectors\test-vectors.json" Link="test-vectors.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
